Import('env', 'plugins')

plugins += env.SharedLibrary('homogeneous', ['homogeneous.cpp'])
plugins += env.SharedLibrary('heterogeneous', ['heterogeneous.cpp'])
plugins += env.SharedLibrary('heterogeneous2', ['heterogeneous2.cpp'])

Export('plugins')
