Import('env', 'plugins')

plugins += env.SharedLibrary('addimages', ['addimages.cpp'])
plugins += env.SharedLibrary('joinrgb', ['joinrgb.cpp'])
plugins += env.SharedLibrary('cylclip', ['cylclip.cpp'])
plugins += env.SharedLibrary('kdbench', ['kdbench.cpp'])
plugins += env.SharedLibrary('tonemap', ['tonemap.cpp'])
#plugins += env.SharedLibrary('rdielprec', ['rdielprec.cpp'])
plugins += env.SharedLibrary('compressvol', ['compressvol.cpp'])
plugins += env.SharedLibrary('readvol', ['readvol.cpp'])

Export('plugins')

